### ISSUE TITLE
Problem with housing shells

### ISSUE THREAD

**Issue by P-iT-Clover** [Mythic-Framework/mythic-framework#3]
**Describe the bug**
When i buy a property for exsmple in forum drive when i enter the house it takes me to mirror park on a standard Coord this happens with every house or warehouse or office  i noticed this to interior 1 -2  it works with mansion because its a gta shell

**Screenshots**
Entering  house 
https://live.staticflickr.com/65535/53783931136_b25150bacb_o.jpg  (Grove St)

Inside house 
https://live.staticflickr.com/65535/53784257394_6088c07d99_o.jpg  (Mirror park)

No server or client errors

**Comment by P-iT-Clover** [comment]
also the phone stuck if you choose the owned property

**Comment by ChrisHaywood90** [comment]
Hi. This happens because the framework uses a routing bucket. When you enter the house, you are teleported into your own "world" lets say. It loads you into the housing shell, which uses Gabz Mirror Park 1 and Mirror Park 2. You need to purchase those assets from Gabz in order for your housing to work correctly.
